input {
    kb_layout = es
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1
    follow_mouse = 2
    float_switch_override_focus = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    inactive_timeout = 60
    no_warps = false
    no_hardware_cursors = false
}

