input {
    kb_layout = es
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    scroll_method = 2fg 

    focus_on_close = 1
    follow_mouse = 2
    float_switch_override_focus = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

device {
    name = hp-hp-400/405-wl-mouse-dongle
    sensitivity = 0
    # Forzamos a que no use los botones para scroll
    scroll_method = none
    # Algunos usuarios reportan que esto ayuda con la detección de clics
    natural_scroll = false
}

cursor {
    hotspot_padding = 1
    inactive_timeout = 60
    no_warps = false
    no_hardware_cursors = false
}

